### ISSUE TITLE
Investigate difficulty of Grammarly's extension

### ISSUE THREAD

**Issue by bernini** [MustWin/irregardless-chrome#31]
I've tried a number of extensions and it seems like Grammarly is best in class in a number of ways. I'd like to understand how difficult pieces of it are so we can prioritize.

To see it in action, check out this video: http://recordit.co/dG0jRBKi4n

- [ ] Add an icon in corner of writing box (the green G)
- [ ] React in almost real-time 
- [ ] Underline words that have corrections
- [ ] Show tip on word hover
- [ ] Click in tip to replace word
- [ ] Ability to toggle on/off checking for a specific site by clicking on icon in add-on bar

![screen shot 2017-02-20 at 12 43 15 pm](https://cloud.githubusercontent.com/assets/3891237/23136316/3599ee2a-f76a-11e6-8bb9-94b01919dbf1.png)

- [ ] Lightbox with additional context and functionality (unlikely we'd want to do this)

**Comment by bernini** [comment]
@johnweldon This might be a good place to start with the Chrome extension. Grammarly's Chrome extension works pretty well so I wanted to understand feasibility of the pieces before finalizing functionality for the Irregardless extension. Is this something you could timebox and give really rough estimates?

**Comment by johnweldon** [comment]
@bernini certainly - I should be able to take an hour or so to make some rough estimates.

**Comment by johnweldon** [comment]
Overall most of these features are not too complicated, most of them are exactly what extensions are geared to do.

Making these features as _polished_ as Grammarly will probably take more time than just getting them working, and that can sometimes take considerably more time due to the iterative and exploratory nature of that kind of refinement.

I've added notes to each below, and grouped a couple that are tightly related.

 - React in almost real time

   This will mostly depend on how fast and responsive the back end webservices are that the chrome extension will rely on, but given well designed and fast API backend, and given that we're careful not to write inefficent code in the plugin, this should be a natural feature of the plugin.



 - Icon in corner of writing box
 - Underline words that have corrections
 - Show tip on word hover

   These three features are all very related, and together are probably a few days work; I'd estimate maybe a week.



 - Click in tip to replace word

   I almost included this in the previous grouping; this probably wouldn't add more than a day or two to the work.



 - Ability to toggle on/off checking for a specific site...

   There would be some implementation questions to answer (should preferences be stored for the user across devices, or just the current device, is one that immediately comes to mind).
   I would expect building out the configuration screen for this to be a few days, maybe a week, and if preferences should be stored across devices maybe a few more days for storing and managing that information on the backend.



 - Lightbox with additional context and functionality

   Depending a lot on the specifics of what would go _in_ this lightbox, probably two or three days for the very basic implementation, and then variable from there.



Any other thoughts or caveats @evertsd, @cousinwil?
