### ISSUE TITLE
When adding new text in body not at end, text not flagged

### ISSUE THREAD

**Issue by bernini** [MustWin/irregardless-chrome#55]
I added another "clearly" up top and it's not being flagged (I confirmed I'm still in the right guide - legal jargon)

![image](https://user-images.githubusercontent.com/3891237/30838070-62782768-a237-11e7-808c-563ec9fbf751.png)

**Comment by evertsd** [comment]
Yeah, unfortunately this is a problem with how we're trying to identify matches atm... It's a bit complicated so bear with me.

At the moment, we find words as such `(^|\\s)clearly(?=(\\s|$|[,.!?:;](\\s|$)))`

What this means is basically this
```
(^|\\s) # this is at the beginning of a line, or is a space
clearly # the word/phrase we're searching for
# the word we're searching for is followed by a space, is the end of a line, or some punctuation
# then after the punctuation there is a space or end of line (makes it so we don't match urls)
(?=(\\s|$|[,.!?:;](\\s|$)))
```

A bit complex, but based on this description we should definitely be matching `clearly` when at the beginning of a document, right?

Well the only problem is that because of how the markup in the "textbox" is structured, matches don't occur at the beginning and end of new lines
```
clearly very unique

cooperation

couldn't care less
```

Actually looks like this to gmail
```
<div class="parent">clearly very unique<div><br><div><div>cooperation</div><div><br></div><div>couldn't care less</div></div>
```

Then, when we parse the text, the tags are removed and it ends up looking like this
```
clearly very uniquecooperationcouldn't care less
```

Because of how this works, I've run the match on each child. The only problem with that is the email doesn't seem to have a consistent structure (although we could probably work to make that happen in a way that's still somewhat friendly to custom formatting)

**Comment by bernini** [comment]
👍
